/**
 * Curated Google Fonts catalog with hand-scored personality vectors.
 * ~30 fonts covering serif, sans-serif, monospace, and display categories.
 *
 * Personality axes (0-100):
 *   temporal:  0 = classic/traditional  →  100 = modern/futuristic
 *   energy:    0 = calm/restrained      →  100 = energetic/bold
 *   tone:      0 = serious/formal       →  100 = friendly/playful
 *   market:    0 = accessible/mass      →  100 = premium/exclusive
 *   density:   0 = airy/minimal         →  100 = dense/rich
 */

export const FONT_CATALOG = [
  // ─── SERIF ────────────────────────────────────────────────────
  {
    family: 'Playfair Display',
    classification: 'serif',
    subclass: 'modern',
    weights_available: [400, 500, 600, 700, 800, 900],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&display=swap',
    x_height_ratio: 0.468,
    personality_scores: { temporal: 25, energy: 55, tone: 30, market: 85, density: 55 },
    role_suitability: { heading: 0.95, body: 0.3, accent: 0.6 },
    is_serif: true,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: false,
    is_bold_optimized: true,
  },
  {
    family: 'Merriweather',
    classification: 'serif',
    subclass: 'traditional',
    weights_available: [300, 400, 700, 900],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap',
    x_height_ratio: 0.500,
    personality_scores: { temporal: 20, energy: 30, tone: 35, market: 55, density: 60 },
    role_suitability: { heading: 0.75, body: 0.85, accent: 0.2 },
    is_serif: true,
    is_traditional: true,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Lora',
    classification: 'serif',
    subclass: 'traditional',
    weights_available: [400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap',
    x_height_ratio: 0.488,
    personality_scores: { temporal: 25, energy: 25, tone: 45, market: 60, density: 50 },
    role_suitability: { heading: 0.7, body: 0.85, accent: 0.3 },
    is_serif: true,
    is_traditional: true,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: false,
  },
  {
    family: 'Libre Baskerville',
    classification: 'serif',
    subclass: 'traditional',
    weights_available: [400, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap',
    x_height_ratio: 0.494,
    personality_scores: { temporal: 15, energy: 20, tone: 20, market: 70, density: 55 },
    role_suitability: { heading: 0.7, body: 0.8, accent: 0.2 },
    is_serif: true,
    is_traditional: true,
    is_modern: false,
    is_light_optimized: false,
    is_bold_optimized: false,
  },
  {
    family: 'Cormorant Garamond',
    classification: 'serif',
    subclass: 'modern',
    weights_available: [300, 400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;500;600;700&display=swap',
    x_height_ratio: 0.420,
    personality_scores: { temporal: 20, energy: 40, tone: 25, market: 90, density: 35 },
    role_suitability: { heading: 0.95, body: 0.4, accent: 0.5 },
    is_serif: true,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: false,
  },
  {
    family: 'DM Serif Display',
    classification: 'serif',
    subclass: 'modern',
    weights_available: [400],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap',
    x_height_ratio: 0.480,
    personality_scores: { temporal: 50, energy: 50, tone: 35, market: 70, density: 50 },
    role_suitability: { heading: 0.90, body: 0.1, accent: 0.6 },
    is_serif: true,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: false,
    is_bold_optimized: false,
  },
  {
    family: 'Bitter',
    classification: 'serif',
    subclass: 'slab',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Bitter:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.510,
    personality_scores: { temporal: 45, energy: 35, tone: 40, market: 40, density: 55 },
    role_suitability: { heading: 0.65, body: 0.80, accent: 0.3 },
    is_serif: true,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Roboto Slab',
    classification: 'serif',
    subclass: 'slab',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'Apache-2.0',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.528,
    personality_scores: { temporal: 55, energy: 40, tone: 30, market: 45, density: 50 },
    role_suitability: { heading: 0.75, body: 0.70, accent: 0.3 },
    is_serif: true,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Source Serif Pro',
    classification: 'serif',
    subclass: 'traditional',
    weights_available: [300, 400, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@300;400;600;700&display=swap',
    x_height_ratio: 0.486,
    personality_scores: { temporal: 30, energy: 25, tone: 25, market: 55, density: 50 },
    role_suitability: { heading: 0.65, body: 0.90, accent: 0.2 },
    is_serif: true,
    is_traditional: true,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: false,
  },
  {
    family: 'Crimson Pro',
    classification: 'serif',
    subclass: 'traditional',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.450,
    personality_scores: { temporal: 15, energy: 20, tone: 30, market: 75, density: 45 },
    role_suitability: { heading: 0.70, body: 0.85, accent: 0.25 },
    is_serif: true,
    is_traditional: true,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },

  // ─── SANS-SERIF ───────────────────────────────────────────────
  {
    family: 'Inter',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.536,
    personality_scores: { temporal: 70, energy: 40, tone: 30, market: 55, density: 40 },
    role_suitability: { heading: 0.6, body: 0.95, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Montserrat',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700, 800, 900],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap',
    x_height_ratio: 0.527,
    personality_scores: { temporal: 65, energy: 55, tone: 35, market: 60, density: 50 },
    role_suitability: { heading: 0.90, body: 0.70, accent: 0.5 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Poppins',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.530,
    personality_scores: { temporal: 70, energy: 50, tone: 55, market: 45, density: 45 },
    role_suitability: { heading: 0.85, body: 0.80, accent: 0.4 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Nunito',
    classification: 'sans-serif',
    subclass: 'humanist',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.536,
    personality_scores: { temporal: 55, energy: 40, tone: 65, market: 35, density: 45 },
    role_suitability: { heading: 0.6, body: 0.90, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'DM Sans',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [400, 500, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap',
    x_height_ratio: 0.534,
    personality_scores: { temporal: 75, energy: 35, tone: 30, market: 60, density: 35 },
    role_suitability: { heading: 0.75, body: 0.90, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: false,
    is_bold_optimized: true,
  },
  {
    family: 'Space Grotesk',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap',
    x_height_ratio: 0.530,
    personality_scores: { temporal: 80, energy: 50, tone: 30, market: 65, density: 40 },
    role_suitability: { heading: 0.85, body: 0.70, accent: 0.5 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Work Sans',
    classification: 'sans-serif',
    subclass: 'humanist',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.520,
    personality_scores: { temporal: 60, energy: 35, tone: 40, market: 45, density: 40 },
    role_suitability: { heading: 0.55, body: 0.90, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Open Sans',
    classification: 'sans-serif',
    subclass: 'humanist',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.536,
    personality_scores: { temporal: 55, energy: 30, tone: 40, market: 40, density: 45 },
    role_suitability: { heading: 0.45, body: 0.95, accent: 0.2 },
    is_serif: false,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Lato',
    classification: 'sans-serif',
    subclass: 'humanist',
    weights_available: [300, 400, 700, 900],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap',
    x_height_ratio: 0.516,
    personality_scores: { temporal: 50, energy: 30, tone: 45, market: 40, density: 45 },
    role_suitability: { heading: 0.5, body: 0.90, accent: 0.2 },
    is_serif: false,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Raleway',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.495,
    personality_scores: { temporal: 60, energy: 40, tone: 40, market: 55, density: 35 },
    role_suitability: { heading: 0.80, body: 0.65, accent: 0.4 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Roboto',
    classification: 'sans-serif',
    subclass: 'neo-grotesque',
    weights_available: [300, 400, 500, 700, 900],
    source: 'google_fonts',
    license: 'Apache-2.0',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap',
    x_height_ratio: 0.528,
    personality_scores: { temporal: 60, energy: 35, tone: 30, market: 40, density: 45 },
    role_suitability: { heading: 0.55, body: 0.90, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Source Sans Pro',
    classification: 'sans-serif',
    subclass: 'humanist',
    weights_available: [300, 400, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap',
    x_height_ratio: 0.486,
    personality_scores: { temporal: 50, energy: 25, tone: 30, market: 50, density: 40 },
    role_suitability: { heading: 0.5, body: 0.90, accent: 0.2 },
    is_serif: false,
    is_traditional: false,
    is_modern: false,
    is_light_optimized: true,
    is_bold_optimized: false,
  },
  {
    family: 'IBM Plex Sans',
    classification: 'sans-serif',
    subclass: 'neo-grotesque',
    weights_available: [300, 400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap',
    x_height_ratio: 0.520,
    personality_scores: { temporal: 65, energy: 30, tone: 20, market: 60, density: 45 },
    role_suitability: { heading: 0.6, body: 0.90, accent: 0.3 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
  {
    family: 'Outfit',
    classification: 'sans-serif',
    subclass: 'geometric',
    weights_available: [300, 400, 500, 600, 700, 800],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap',
    x_height_ratio: 0.530,
    personality_scores: { temporal: 80, energy: 45, tone: 45, market: 50, density: 40 },
    role_suitability: { heading: 0.80, body: 0.80, accent: 0.4 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },

  // ─── MONOSPACE ────────────────────────────────────────────────
  {
    family: 'JetBrains Mono',
    classification: 'monospace',
    subclass: 'monospace',
    weights_available: [400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap',
    x_height_ratio: 0.530,
    personality_scores: { temporal: 80, energy: 35, tone: 25, market: 55, density: 50 },
    role_suitability: { heading: 0.2, body: 0.3, accent: 0.95 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: false,
    is_bold_optimized: true,
  },
  {
    family: 'Fira Code',
    classification: 'monospace',
    subclass: 'monospace',
    weights_available: [300, 400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap',
    x_height_ratio: 0.530,
    personality_scores: { temporal: 75, energy: 30, tone: 30, market: 50, density: 50 },
    role_suitability: { heading: 0.2, body: 0.3, accent: 0.90 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },

  // ─── DISPLAY ──────────────────────────────────────────────────
  {
    family: 'Bebas Neue',
    classification: 'display',
    subclass: 'display',
    weights_available: [400],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap',
    x_height_ratio: 0.700,
    personality_scores: { temporal: 55, energy: 85, tone: 40, market: 45, density: 70 },
    role_suitability: { heading: 0.95, body: 0.0, accent: 0.7 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: false,
    is_bold_optimized: false,
  },
  {
    family: 'Oswald',
    classification: 'display',
    subclass: 'display',
    weights_available: [300, 400, 500, 600, 700],
    source: 'google_fonts',
    license: 'OFL',
    google_fonts_url: 'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap',
    x_height_ratio: 0.590,
    personality_scores: { temporal: 50, energy: 70, tone: 35, market: 40, density: 65 },
    role_suitability: { heading: 0.90, body: 0.15, accent: 0.6 },
    is_serif: false,
    is_traditional: false,
    is_modern: true,
    is_light_optimized: true,
    is_bold_optimized: true,
  },
];

/** Look up a single font by family name. */
export function getFontByFamily(family) {
  return FONT_CATALOG.find(f => f.family === family) || null;
}

/** All serif fonts. */
export function getSerifs() {
  return FONT_CATALOG.filter(f => f.classification === 'serif');
}

/** All sans-serif fonts. */
export function getSansSerifs() {
  return FONT_CATALOG.filter(f => f.classification === 'sans-serif');
}

/** All monospace fonts. */
export function getMonospaces() {
  return FONT_CATALOG.filter(f => f.classification === 'monospace');
}

/** All display fonts. */
export function getDisplayFonts() {
  return FONT_CATALOG.filter(f => f.classification === 'display');
}

/** Filter by subclass (geometric, humanist, traditional, modern, slab, display, monospace, neo-grotesque). */
export function getFontsBySubclass(subclass) {
  return FONT_CATALOG.filter(f => f.subclass === subclass);
}
