-- Enhance daily_journals table with AI-generated content columns
-- These columns support the rich narrative daily journals feature

-- Add summary points as a JSONB array of bullet points
ALTER TABLE daily_journals ADD COLUMN IF NOT EXISTS summary_points JSONB DEFAULT '[]'::jsonb;

-- Add timeline narrative for chronological day description
ALTER TABLE daily_journals ADD COLUMN IF NOT EXISTS timeline_narrative TEXT;

-- Add personal notes/insights section
ALTER TABLE daily_journals ADD COLUMN IF NOT EXISTS personal_notes TEXT;

-- Add weekly context for tracking progress over time
ALTER TABLE daily_journals ADD COLUMN IF NOT EXISTS weekly_context TEXT;

-- Flag to indicate if journal was AI-generated vs deterministic
ALTER TABLE daily_journals ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;

-- Add comment for documentation
COMMENT ON COLUMN daily_journals.summary_points IS 'Array of bullet point summaries generated by AI';
COMMENT ON COLUMN daily_journals.timeline_narrative IS 'Chronological narrative of the day with timestamps';
COMMENT ON COLUMN daily_journals.personal_notes IS 'AI-generated insights and observations';
COMMENT ON COLUMN daily_journals.weekly_context IS 'Context comparing to previous days in the week';
COMMENT ON COLUMN daily_journals.ai_generated IS 'True if journal was generated with LLM, false if deterministic';
