-- Pending Actions: Notch action approval system
-- Stores actions detected by local MLX model and enriched by cloud for user approval

CREATE TABLE IF NOT EXISTS public.pending_actions (
  id UUID PRIMARY KEY,                              -- generated by desktop
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  company_id UUID NOT NULL,

  -- Display
  title TEXT NOT NULL,                               -- notch notification text (max 60 chars)
  subtitle TEXT,                                     -- optional detail line

  -- Action definition
  action_type TEXT NOT NULL,                         -- calendar_event, task_create, email_reply, reminder, etc.
  action_payload JSONB NOT NULL DEFAULT '{}',        -- full execution details

  -- Detection context
  event_hash TEXT NOT NULL,                          -- dedup fingerprint
  trigger_context JSONB,                             -- the context event that caused detection
  local_confidence REAL,                             -- MLX model confidence (0-1)
  cloud_confidence REAL,                             -- cloud validation confidence (0-1)

  -- Lifecycle
  status TEXT NOT NULL DEFAULT 'pending',
  status_message TEXT,                               -- "Already in calendar", "Failed: auth expired", etc.

  created_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ DEFAULT (now() + interval '1 hour'),

  CONSTRAINT unique_event UNIQUE (user_id, event_hash)
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_pending_actions_user_status
  ON public.pending_actions(user_id, status);

CREATE INDEX IF NOT EXISTS idx_pending_actions_expires
  ON public.pending_actions(expires_at) WHERE status = 'pending';

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.pending_actions;

-- Row Level Security
ALTER TABLE public.pending_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own actions" ON public.pending_actions
  FOR ALL TO authenticated
  USING (user_id = auth_uid());

-- Auto-expire old pending actions
-- Sets status to 'expired' for any pending actions past their expires_at
CREATE OR REPLACE FUNCTION public.expire_pending_actions()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  expired_count INTEGER;
BEGIN
  UPDATE public.pending_actions
  SET status = 'expired',
      status_message = 'Auto-expired after TTL',
      resolved_at = now()
  WHERE status = 'pending'
    AND expires_at < now();

  GET DIAGNOSTICS expired_count = ROW_COUNT;
  RETURN expired_count;
END;
$$;
